### ISSUE TITLE
Create the Wireframes and Lo-fi for the Terms of Service Page

### ISSUE THREAD

**Issue by tersoo-ahire** [zuri-training/Chunk-File-Generator-Team-50#11]

**Comment by Lois1221** [comment]
@tersoo-ahire  I have created the wireframe for this page. The lo-fi requires the audience of the designers because it requires UX Writing which would be discussed in the next meeting we'll have on Figma.
Question: Can you use the wireframe alone to do you need the lo-fi to make the page responsive? Although they would only need a tick box.

**Comment by tersoo-ahire** [comment]
https://www.figma.com/file/HDodbxGZGTlpZFJKqWSV2C/Team-50-Chunk-Files?node-id=541%3A184
